version: '3.8'

services:
  flask_app:
    build:
      context: ./src
      dockerfile: ../docker/Dockerfile
    ports:
      - "500:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=development
    networks:
      - devops_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alunos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - devops_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoramento/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - devops_network


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - devops_network

volumes:
  db_data:

networks:
  devops_network:
    driver: bridge
