global:
  scrape_interval: 15s # Intervalo padrão de coleta de métricas para todos os jobs

scrape_configs:
  - job_name: "prometheus" # Nome do job para o Prometheus
    static_configs:
      - targets: ["prometheus:9090"] # Nome do serviço para o próprio Prometheus

  - job_name: "mysqld_exporter" # Nome do job para o MySQL Exporter
    static_configs:
      - targets: ["mysqld_exporter:9104"] # Nome do serviço para o MySQL Exporter
