FROM grafana/grafana:latest

# Copiar os arquivos de provisionamento
COPY provisioning/datasources/ /etc/grafana/provisioning/datasources/
COPY provisioning/dashboards/ /etc/grafana/provisioning/dashboards/

# Copiar os dashboards JSON
COPY dashboards/ /var/lib/grafana/dashboards/

# Permitir que o Grafana leia os arquivos
USER root
RUN chmod -R 755 /etc/grafana /var/lib/grafana
USER grafana